export const AUTOSAVE_INTERVAL_IN_MS = 60 * 1000
export const GAME_SAVE_LOCAL_STORAGE_KEY = "ANT-INCREMENTAL-SAVE"

export const TARGET_RENDER_WIDTH_IN_PX = 1920
export const TARGET_RENDER_HEIGHT_IN_PX = 969

export const GENERATOR_BASE_PRICE_INCREASE = 1.5
